---
title: "About"
format: 
  html:
    execute:
      allow-html: true
---

I am a PhD candidate in the Political Science Department at McGill University in Montréal.

My research interests are at the intersection of comparative political economy, political behaviour and communication. My dissertation investigates the governance of emerging economic markets in Central and Eastern European countries, its relationship to state capacity and its impact on economic and political preferences at the individual and firm level.

I am also interested in issues pertaining to identifying and measuring misinformation both from the supply and demand sides in a multi-methods perspective. My research projects and academic training have led me to acquire methodological training in quantitative (survey, experimental & causal inference designs), and qualitative methods (interviews, focus-groups, field observations) as well as approaches mobilizing both, such as natural language processing.

Previously, I completed a Master's degree in Political Science and International Relations at the University of Quebec at Montreal, where my dissertation on the construction of Russia's revanchist identity and the annexation of Crimea obtained a mention of excellence by the Jury.

Beyond of Political Science, I'm fond of data science, astrophysics and linguistics.

Outside of academia, I'm an avid fan of cycling, botany, a weekend trumpeter, and sometimes an experimental baker.

Here is my CV:

<iframe src="files/CV_DavidDube.pdf" width="100%" height="800px" style="border: none;">
This browser does not support PDFs. Please download the PDF to view it: 
<a href="files/CV_DavidDube.pdf">Download PDF</a>.
</iframe>
