---
title: "Research & Publications"
---

My research interests are at the intersection of comparative political economy, political behaviour and communication. My dissertation investigates the governance of emerging economic markets in Central and Eastern European countries, its relationship to state capacity and its impact on economic and political preferences at the individual (civilians and elites) and firm level.

I am also interested in issues pertaining to identifying and measuring misinformation both from the supply and demand sides in a multi-methods perspective, using quantitative (survey, experimental & causal inference designs), qualitative (interviews, focus-groups, field observations) and approaches at the convergence of both (e.g. large language models).

*Research Projects:*

**Authoritarian Global Foreign Disinformation Strategies:** This research, in collaboration with Prof. Jean-Christophe Boucher (University of Calgary) investigates the foreign disinformation strategies of China and Russia on social media platforms (Twitter/X, Telegram, Facebook) in Western and Global South countries. We leverage unsupervised natural language processing (NLP) models to analyze and structure Chinese and Russian strategies and narratives in a data-driven fashion to enable the construction of a theoretical framework of authoritarian foreign disinformation.

This research stems from the willingness to use highly strategically-structured and centralized state-disseminated (dis)information to make sense of the much broader complex ecosystem of authoritarian disinformation.

**Cross-Country Diaspora Survey Matching:** This research seeks to build a survey-experimental design on the media consumption practices of Chinese, Russian and Indian diasporas living in the United States and Canada. The goal is to match these individuals with co-nationals in their home countries to investigate the relationship between media consumption, political preferences and behaviour. This research seeks to promote the use of pre-registration and pre-acceptance publication mechanisms as ways to promote the development of more rigorous research design, research transparency, replicability and incentivize exploratory research by encouraging the publication of null and negative results.

**Russian Emigrants in the Former Soviet Union:** Leveraging vignette survey experiment data of Russian citizens living who left Russia to live in other former soviet republics, this study investigates the political preferences and investigates their political preferences. It also explores the determinants most likely to influence their willingness to move back to Russia. This research is part of a broader research program for scholars of the Former Soviet Union and authoritarian regimes who seek to refine their techniques of ethical data collection surrounding political behaviour in authoritatian context.

*Working Papers:*

Dubé D., Boucher J-C, "Whispers from the Kremlin: Inoculating Against Russian Propaganda in the Global South", Presented at APSA 2024 in Philadelphia. Available here:

Dubé D., "Should I Stay of Should I go? The Determinants of Russian Emigrants Willingness to Return Home". Available here:

*Peer Reviewed Book Chapter:*

Dubé D (2024). "Baby You Can Drive my Car: From Trump to Biden, the US-Canada Auto Industry Commercial Policy, in Gagnon F., Cloutier-Roy F. (eds), America First, Then Canada, University of Montreal Press, pp.55-68.
